Nouveau script de chargement des données
georchestra/cadastrapp pull request #568
Opened 2021-06-17 19:43 UTC by MaelREBOUX

fix #553

2021-06-21 08:34 UTC, jusabatier requested changes
Après test du script, quelques changements à faire.

Je vais à présent tester si les données remontent correctement dans l'addon.

2021-06-21 08:34 UTC, jusabatier commented on database/create_views.sh
> +  replaceAndLaunch sql/vues/commune.sql
Remplacer par **C**ommune.sql

2021-06-21 08:34 UTC, jusabatier commented on database/create_views.sh
> +  replaceAndLaunch sql/vues_dblink/commune.sql
Remplacer par Commune.sql

2021-06-21 08:34 UTC, jusabatier commented on database/sql/vues/Parcelle.sql
> +			left join cadastrapp.v_parcelle_surfc p2 on parcelle.parcelle=p2.parcelle
Remplacer cadastrapp par #schema_cadastrapp pour le schema

2021-06-21 08:34 UTC, jusabatier commented on database/tables_request.sh
> +    --field-separator ' ' `
Affiche une erreur lors de l’exécution si la table n'existe pas : 

```
ERREUR:  la relation « cadastrapp_local.request_information » n'existe pas
LIGNE 1 : SELECT count(*) FROM cadastrapp_local.request_information ;
```

Le script continue normalement après mais ça fait bizarre de voir l'erreur apparaitre.

Il faudrait remplacer par :
```
    --field-separator ' ' &>/dev/null `
```

2021-06-21 08:49 UTC, jusabatier requested changes
La table https://github.com/georchestra/cadastrapp/blob/issue_553/script/commun/user/groupe_autorisation.sql n'est pas créée par le script, on a donc une erreur lors de l'utilisation de l'addon.

2021-06-22 14:42 UTC, jusabatier requested changes

2021-06-22 14:42 UTC, jusabatier commented on database/sql/vues/Proprietaire.sql
> +				WHEN gtoper = '1' THEN COALESCE(rtrim(dqualp),'')||' '||COALESCE(rtrim(dnomlp),'')||' '||COALESCE(rtrim(dprnlp),'')
Cf. https://github.com/georchestra/cadastrapp/issues/569

2021-06-22 14:42 UTC, jusabatier commented on database/sql/vues_dblink/Proprietaire.sql
> +				WHEN gtoper = ''1'' THEN COALESCE(rtrim(dqualp),'''')||'' ''||COALESCE(rtrim(dnomlp),'''')||'' ''||COALESCE(rtrim(dprnlp),'''')
Cf. https://github.com/georchestra/cadastrapp/issues/569

2021-07-06 13:27 UTC, MaelREBOUX commented
Bien vu pour oubli groupe_autorisation. Merci.

2021-07-06 13:32 UTC, merged